<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Errors Ruff 1.5.0 Manual &amp; Documentation</title>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic">
  <link rel="stylesheet" href="assets/style.css">
  <link rel="stylesheet" href="assets/sh.css">
  <link rel="canonical" href="https://ruff.io/api/errors.html">
</head>
<body class="alt apidoc" id="api-section-errors">
  <div id="content" class="clearfix">
    <div id="column1" data-id="errors" class="interior">
      <header>
        <h1>Ruff 1.5.0 Documentation</h1>
        <hr>
      </header>

      <div id="toc">
        <h2>Table of Contents</h2>
        <ul>
<li><a href="#errors_errors">Errors</a><ul>
<li><a href="#errors_javascript_errors">JavaScript Errors</a><ul>
<li><a href="#errors_class_error">Class: Error</a><ul>
<li><a href="#errors_new_error_message">new Error(message)</a></li>
<li><a href="#errors_error_message">error.message</a></li>
<li><a href="#errors_error_stack">error.stack</a></li>
<li><a href="#errors_error_capturestacktrace_targetobject_constructoropt">Error.captureStackTrace(targetObject[, constructorOpt])</a></li>
<li><a href="#errors_error_stacktracelimit">Error.stackTraceLimit</a></li>
</ul>
</li>
<li><a href="#errors_class_rangeerror">Class: RangeError</a></li>
<li><a href="#errors_class_typeerror">Class: TypeError</a></li>
<li><a href="#errors_class_referenceerror">Class: ReferenceError</a></li>
<li><a href="#errors_class_syntaxerror">Class: SyntaxError</a></li>
<li><a href="#errors_exceptions_vs_errors">Exceptions vs. Errors</a></li>
</ul>
</li>
</ul>
</li>
</ul>

      </div>

      <div id="apicontent">
        <h1 id="errors-span-a-class-mark-href-errors_errors-id-errors_errors-a-span-">Errors<span><a class="mark" href="#errors_errors" id="errors_errors">#</a></span></h1>
<!--type=misc-->
<p>Errors generated by Ruff fall into two categories: JavaScript errors and system
errors. All errors inherit from or are instances of JavaScript&#39;s <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error">Error</a>
class and are guaranteed to provide <em>at least</em> the attributes available on that
class.</p>
<p>When an operation is not permitted due to language-syntax or
language-runtime-level reasons, a <strong>JavaScript error</strong> is generated and thrown
as an <strong>exception</strong>. If an operation is not allowed due to system-level
restrictions, a <strong>system error</strong> is generated. Client code is then given the
opportunity to <strong>intercept</strong> this error based on how the API <strong>propagates</strong> it.</p>
<p>The style of API called determines how generated errors are handed back, or
<strong>propagated</strong>, to client code, which in turn informs how the client may <strong>intercept</strong>
the error. Exceptions can be intercepted using the <code>try / catch</code> construct;
other propagation strategies are covered <a href="#errors_error_propagation_and_interception">below</a>.</p>
<h2 id="javascript-errors-span-a-class-mark-href-errors_javascript_errors-id-errors_javascript_errors-a-span-">JavaScript Errors<span><a class="mark" href="#errors_javascript_errors" id="errors_javascript_errors">#</a></span></h2>
<!--type=misc-->
<p>JavaScript errors typically denote that an API is being used incorrectly, or that
there is a problem with the program as written.</p>
<h3 id="class-error-span-a-class-mark-href-errors_class_error-id-errors_class_error-a-span-">Class: Error<span><a class="mark" href="#errors_class_error" id="errors_class_error">#</a></span></h3>
<!--type=class-->
<p>A general error object. Unlike other error objects, <code>Error</code> instances do not
denote any specific circumstance of why the error occurred. Errors capture a
&quot;stack trace&quot; detailing the point in the program at which they were
instantiated, and may provide a description of the error.</p>
<p><strong>Note</strong>: Ruff will generate this class of error to encapsulate system
errors as well as plain JavaScript errors.</p>
<h4 id="new-error-message-span-a-class-mark-href-errors_new_error_message-id-errors_new_error_message-a-span-">new Error(message)<span><a class="mark" href="#errors_new_error_message" id="errors_new_error_message">#</a></span></h4>
<p>Instantiates a new Error object and sets its <code>.message</code> property to the provided
message. Its <code>.stack</code> will represent the point in the program at which <code>new Error</code>
was called. Stack traces are subject to <a href="https://github.com/svaarala/duktape/blob/master/doc/error-objects.rst">Duktape&#39;s stack trace API</a>.
Stack traces only extend to the beginning of synchronous code execution, <em>or</em> a number of frames given by
<code>Error.stackTraceLimit</code>, whichever is smaller.</p>
<h4 id="error-message-span-a-class-mark-href-errors_error_message-id-errors_error_message-a-span-">error.message<span><a class="mark" href="#errors_error_message" id="errors_error_message">#</a></span></h4>
<p>A string of the value passed to <code>Error()</code> upon instantiation. The message will
also appear in the first line of the stack trace of the error. Changing this
property <em>may not</em> change the first line of the stack trace.</p>
<h4 id="error-stack-span-a-class-mark-href-errors_error_stack-id-errors_error_stack-a-span-">error.stack<span><a class="mark" href="#errors_error_stack" id="errors_error_stack">#</a></span></h4>
<p>A property that, when <strong>accessed</strong>, returns a string representing the point in the program
at which this error was instantiated. An example stacktrace follows:</p>
<pre><code>AssertionError: 6 == 9
  fail /Users/zhulizhong/ruff/ruff_modules/assert/src/index.js:93
  equal /Users/zhulizhong/ruff/ruff_modules/assert/src/index.js:119
  anon /Users/zhulizhong/ruff/ruff_modules/timers/test/timers_test.js:32 preventsyield
  anon  native strict preventsyield
</code></pre><p>The first line is formatted as <code>&lt;error class name&gt;: &lt;error message&gt;</code>, and it is followed
by a series of stack frames (each line beginning with method name). Each frame describes
a call site in the program that lead to the error being generated. Duktape attempts to
display a name for each function (by variable name, function name, or object
method name), but occasionally it will not be able to find a suitable name. </p>
<p>Frames are <strong>only</strong> generated for JavaScript functions. If, for example, execution
synchronously passes through a C++ addon function called <code>cheetahify</code>, which itself
calls a JavaScript function, the frame representing the <code>cheetahify</code> call will <strong>not</strong>
be present in stacktraces:</p>
<pre><code class="lang-javascript">var cheetahify = require(&#39;./native-binding.node&#39;);

function makeFaster() {
  // cheetahify *synchronously* calls speedy.
  cheetahify(function speedy() {
    throw new Error(&#39;oh no!&#39;);
  });
}

makeFaster(); // will throw:
// /home/gbusey/file.js:6
//     throw new Error(&#39;oh no!&#39;);
//           ^
// Error: oh no!
//      makeFaster speedy (/home/gbusey/file.js:6:11)
//      fail /Users/zhulizhong/ruff/ruff_modules/assert/src/index.js:93
//      equal /Users/zhulizhong/ruff/ruff_modules/assert/src/index.js:119
//      anon /Users/zhulizhong/ruff/ruff_modules/timers/test/timers_test.js:32 preventsyield
//      anon  native strict preventsyield
</code></pre>
<p>The location information will be one of:</p>
<ul>
<li><code>native</code>, if the frame represents a call internal to Duktape (as in <code>[].forEach</code>).</li>
<li><code>plain-filename.js:line:column</code>, if the frame represents a call internal to Ruff.</li>
<li><code>/absolute/path/to/file.js:line</code>, if the frame represents a call in a user program, or its dependencies.</li>
</ul>
<p>It is important to note that the string representing the stacktrace is only
generated on <strong>access</strong>: it is lazily generated.</p>
<p>The number of frames captured by the stack trace is bounded by the smaller of
<code>Error.stackTraceLimit</code> or the number of available frames on the current event
loop tick.</p>
<p>System-level errors are generated as augmented Error instances, which are detailed
<a href="#errors_system_errors">below</a>.</p>
<h4 id="error-capturestacktrace-targetobject-constructoropt-span-a-class-mark-href-errors_error_capturestacktrace_targetobject_constructoropt-id-errors_error_capturestacktrace_targetobject_constructoropt-a-span-">Error.captureStackTrace(targetObject[, constructorOpt])<span><a class="mark" href="#errors_error_capturestacktrace_targetobject_constructoropt" id="errors_error_capturestacktrace_targetobject_constructoropt">#</a></span></h4>
<p>Creates a <code>.stack</code> property on <code>targetObject</code>, which when accessed returns
a string representing the location in the program at which <code>Error.captureStackTrace</code>
was called.</p>
<pre><code class="lang-javascript">var myObject = {};

Error.captureStackTrace(myObject);

myObject.stack  // similar to `new Error().stack`
</code></pre>
<p>The first line of the trace, instead of being prefixed with <code>ErrorType:
message</code>, will be the result of <code>targetObject.toString()</code>.</p>
<p><code>constructorOpt</code> optionally accepts a function. If given, all frames above
<code>constructorOpt</code>, including <code>constructorOpt</code>, will be omitted from the generated
stack trace.</p>
<p>This is useful for hiding implementation details of error generation from the
end user. A common way of using this parameter is to pass the current Error
constructor to it:</p>
<pre><code class="lang-javascript">
function MyError() {
  Error.captureStackTrace(this, MyError);
}

// without passing MyError to captureStackTrace, the MyError
// frame would should up in the .stack property. by passing
// the constructor, we omit that frame and all frames above it.
new MyError().stack
</code></pre>
<h4 id="error-stacktracelimit-span-a-class-mark-href-errors_error_stacktracelimit-id-errors_error_stacktracelimit-a-span-">Error.stackTraceLimit<span><a class="mark" href="#errors_error_stacktracelimit" id="errors_error_stacktracelimit">#</a></span></h4>
<p>Property that determines the number of stack frames collected by a stack trace
(whether generated by <code>new Error().stack</code> or <code>Error.captureStackTrace(obj)</code>).</p>
<p>The initial value is <code>10</code>. It may be set to any valid JavaScript number, which
will affect any stack trace captured <em>after</em> the value has been changed. If set
to a non-number value, stack traces will not capture any frames and will report
<code>undefined</code> on access.</p>
<h3 id="class-rangeerror-span-a-class-mark-href-errors_class_rangeerror-id-errors_class_rangeerror-a-span-">Class: RangeError<span><a class="mark" href="#errors_class_rangeerror" id="errors_class_rangeerror">#</a></span></h3>
<p>A subclass of Error that indicates that a provided argument was not within the
set or range of acceptable values for a function; whether that be a numeric
range, or outside the set of options for a given function parameter. An example:</p>
<pre><code class="lang-javascript">require(&#39;net&#39;).connect(-1);  // throws RangeError, port should be &gt; 0 &amp;&amp; &lt; 65536
</code></pre>
<p>Ruff will generate and throw RangeError instances <em>immediately</em> -- they are a form
of argument validation.</p>
<h3 id="class-typeerror-span-a-class-mark-href-errors_class_typeerror-id-errors_class_typeerror-a-span-">Class: TypeError<span><a class="mark" href="#errors_class_typeerror" id="errors_class_typeerror">#</a></span></h3>
<p>A subclass of Error that indicates that a provided argument is not an allowable
type. For example, passing a function to a parameter which expects a string would
be considered a TypeError.</p>
<pre><code class="lang-javascript">require(&#39;url&#39;).parse(function() { }); // throws TypeError, since it expected a string
</code></pre>
<p>Ruff will generate and throw TypeError instances <em>immediately</em> -- they are a form
of argument validation.</p>
<h3 id="class-referenceerror-span-a-class-mark-href-errors_class_referenceerror-id-errors_class_referenceerror-a-span-">Class: ReferenceError<span><a class="mark" href="#errors_class_referenceerror" id="errors_class_referenceerror">#</a></span></h3>
<p>A subclass of Error that indicates that an attempt is being made to access a variable
that is not defined. Most commonly it indicates a typo, or an otherwise broken program.
While client code may generate and propagate these errors, in practice only Duktape will do
so.</p>
<pre><code class="lang-javascript">doesNotExist; // throws ReferenceError, doesNotExist is not a variable in this program.
</code></pre>
<p>ReferenceError instances will have an <code>.arguments</code> member that is an array containing
one element -- a string representing the variable that was not defined.</p>
<pre><code class="lang-javascript">try {
  doesNotExist;
} catch(err) {
  err.arguments[0] === &#39;doesNotExist&#39;;
}
</code></pre>
<p>Unless the userland program is dynamically generating and running code,
ReferenceErrors should always be considered a bug in the program, or its
dependencies.</p>
<h3 id="class-syntaxerror-span-a-class-mark-href-errors_class_syntaxerror-id-errors_class_syntaxerror-a-span-">Class: SyntaxError<span><a class="mark" href="#errors_class_syntaxerror" id="errors_class_syntaxerror">#</a></span></h3>
<p>A subclass of Error that indicates that a program is not valid JavaScript.
These errors may only be generated and propagated as a result of code
evaluation. Code evaluation may happen as a result of <code>eval</code>, <code>Function</code>,
<code>require</code>, or <a href="vm.html">vm</a>. These errors are almost always indicative of a broken
program.</p>
<pre><code class="lang-javascript">try {
  require(&quot;vm&quot;).runInThisContext(&quot;binary ! isNotOk&quot;);
} catch(err) {
  // err will be a SyntaxError
}
</code></pre>
<p>SyntaxErrors are unrecoverable from the context that created them – they may only be caught
by other contexts.</p>
<h3 id="exceptions-vs-errors-span-a-class-mark-href-errors_exceptions_vs_errors-id-errors_exceptions_vs_errors-a-span-">Exceptions vs. Errors<span><a class="mark" href="#errors_exceptions_vs_errors" id="errors_exceptions_vs_errors">#</a></span></h3>
<!--type=misc-->
<p>A JavaScript &quot;exception&quot; is a value that is thrown as a result of an invalid operation or
as the target of a <code>throw</code> statement. While it is not required that these values inherit from
<code>Error</code>, all exceptions thrown by Ruff or the JavaScript runtime <em>will</em> be instances of Error.</p>
<p>Some exceptions are <em>unrecoverable</em> at the JavaScript layer. These exceptions will always bring
down the process. These are usually failed <code>assert()</code> checks or <code>abort()</code> calls in the C++ layer.</p>

      </div>
    </div>
  </div>
  <div id="footer">
  </div>

  <script src="assets/sh_main.js"></script>
  <script src="assets/sh_javascript.min.js"></script>
  <script>highlight(undefined, undefined, 'pre');</script>
</body>
</html>

